### ISSUE TITLE
upstream dependencies should be downstream dependents

### ISSUE THREAD

**Issue by oxinabox** [JuliaEcosystem/PkgDeps.jl#12]
If X uses Y, then:
 - Y is a dependency of X
 - Y is upstrean of X
 - X is a dependant of Y
 - X is downstream from Y.
 
 
 It seems like the packages is using these words backwards

**Comment by mattBrzezinski** [comment]
Ah yes, thanks!

**Comment by ericphanson** [comment]
It looks like this was fixed by #15, though actually I find the change there from "UpDep" to "DownDep" a bit confusing, since that package is upstream from all other packages in the test system, so I think the name "UpDep" is more appropriate; it's the uppermost dep.

**Comment by nickrobinson251** [comment]
i'm still confused by the naming. `upstream_dependencies` previously had the opposite meaning to what i expected, but now (post-#15) it is named `downstream_dependencies` which is a contradiction: as Lyndon says, dependecies are "upstream" and _dependents_ are "downstream"

If someone says "downstream", i think users of the package (i.e. dependents)
If someone says "dependencies, i think stuff the package depends on (i.e. "upstream") 
Hence, "downstream dependencies" makes my head spin :joy: 

i'd expect something like either
```julia
downstream_deps(MyPkg)
upstream_deps(MyPkg)
```
or 
```julia
dependents(MyPkg)
dependencies(MyPkg)
```
or even
```julia
downstream_dependents(MyPkg)
upstream_dependencies(MyPkg)
```
(i know this is a bit bikeshed-y, but i think it does affect useability a bit)

**Comment by mattBrzezinski** [comment]
Yeah this is a bit confusing, I think `dependents` and `dependencies` are much more clear and avoid this confusion.

**Comment by nickrobinson251** [comment]
> I find the change there from "UpDep" to "DownDep" a bit confusing...

i agree with Eric on this too :)

**Comment by ericphanson** [comment]
in #16 I use `dependencies` to mean the usual thing ("upstream") and `find_downstream_dependencies` for downstream. To me it doesn't seem too confusing which is which if those are the choices ("dependencies" vs "downstream dependencies"). I think `dependents` works too, but `dependents` vs `dependencies` can feel a bit too similar somehow.

**Comment by nickrobinson251** [comment]
> I use `dependencies` to mean the usual thing ("upstream")

🎉 

I think `downstream_dependencies` will always make my head hurt 😂 I'd prefer "dependents" but maybe we can avoid something too similar altogether... perhaps somethng like `find_downstream_users` is an option?

**Comment by mattBrzezinski** [comment]
In my mind:

- `dependencies`: what the package is using, basically whatever is in the `Project.toml`
- `dependents`: what packages are using your package

I think this simplifies things a lot more than bringing in `up/down streams` as I feel this discussion will need to be summarized in the `README` so others can understand lol

**Comment by ericphanson** [comment]
what do you think of Nick's "users"? I like that, since it's a more common word / more intuitive than "dependents". So then there's the helpfully asymmetric:

* `dependencies`: what the package is using, basically whatever is in the Project.toml
* `users`: which packages are using your package
