### ISSUE TITLE
use UUIDs instead of names?

### ISSUE THREAD

**Issue by ericphanson** [JuliaEcosystem/PkgDeps.jl#17]
Currently, PkgDeps uses names to represent unique packages, e.g.

https://github.com/JuliaEcosystem/PkgDeps.jl/blob/f70f26c8d104af4f4f5fb364f0c9bc6a58d1785f/src/registry_instance.jl#L8

uses package names as keys. I think probably most usages of the package names should instead be UUIDs, or maybe a type consisting of a  (UUID, name) pair where the name is printed for readability. Since two different registries can have packages with the same name representing different packages (with different UUIDs).

**Comment by mattBrzezinski** [comment]
I wrote this using PackageNames as it's both more quicker and easier to look them up from a human perspective. UUIDs would simplify and remove this issue or handling multiple registries with same named packages in them though.

Might be worthwhile to simplify this into using UUIDs and having a more human friendly interface for calling in. Could even be something taking in the package name, a default arg to the general registry and then finding the UUID for that and using that going forward?

**Comment by ericphanson** [comment]
Yeah, I like the quick and intuitive aspect of the names. Thinking about it a bit more, I think actually that changing it in `RegistryInstance` is probably unnecessary, since there should usually be a unique package name to package UUID mapping within a single registry (at least, RegistryCI tries to enforce this, although there could be noncompliant registries AFAIK), and the `pkgs` field essentially holds that mapping.

I think where disambiguation might be needed is when checking if a given package name matches another one from possibly another registry, such as in https://github.com/JuliaEcosystem/PkgDeps.jl/blob/f70f26c8d104af4f4f5fb364f0c9bc6a58d1785f/src/PkgDeps.jl#L120. There, ideally we would be comparing either UUIDs or (name, UUID) pairs, instead of just names.

> Could even be something taking in the package name, a default arg to the general registry and then finding the UUID for that and using that going forward?

Yeah, I like that. So the input to the API functions (`dependencies`, `dependents`, or however we decide on #12) could accept either a package name (in which case the UUID would be looked up, and possibly a warning or error could be given if there are multiple matches from different registries) or just a UUID in which case the name would similarly be looked up, or a (name, UUID) pair. Then the output of `dependencies`, `dependents`, etc, should likewise be a list (package name, UUID) pairs, otherwise there's the same disambiguation problem later on.

I think outputting pairs might be a bit annoying for casual use, but something fun that might work would be to make a type that holds those two fields (pkg name, package UUID), and is a subtype of AbstractString, and acts like just the package name when used as a string. So essentially you can treat it as getting back a list of strings, except you additionally have the UUIDs sitting there in case you need to use them.

**Comment by mattBrzezinski** [comment]
> Yeah, I like that. So the input to the API functions (`dependencies`, `dependents`, or however we decide on #12) could accept either a package name (in which case the UUID would be looked up, and possibly a warning or error could be given if there are multiple matches from different registries) or just a UUID in which case the name would similarly be looked up, or a (name, UUID) pair. Then the output of `dependencies`, `dependents`, etc, should likewise be a list (package name, UUID) pairs, otherwise there's the same disambiguation problem later on.

Yeah I think something like below, where we default to the general registry and users can override it.

```julia
users("package-name"; repository="General")
users(uuid)
```

One thing however is the uniqueness of registry names which should be considered.

> I think outputting pairs might be a bit annoying for casual use, but something fun that might work would be to make a type that holds those two fields (pkg name, package UUID), and is a subtype of AbstractString, and acts like just the package name when used as a string. So essentially you can treat it as getting back a list of strings, except you additionally have the UUIDs sitting there in case you need to use them.

Could have a verbosity option here for the tuple part, and just default to something reasonable.
