### ISSUE TITLE
Make `users` more helpful when package name not found

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaEcosystem/PkgDeps.jl#19]
Current behaviour (in v0.3)
```julia
julia> users("ParameterJUMP")
ERROR: ParameterJUMP not in General

Stacktrace:
 [1] _get_pkg_uuid(pkg_name::String, registry_name::String; depots::Vector{String}, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ PkgDeps ~/.julia/packages/PkgDeps/6nJkw/src/PkgDeps.jl:66
 [2] _get_pkg_uuid
   @ ~/.julia/packages/PkgDeps/6nJkw/src/PkgDeps.jl:61 [inlined]
 [3] #users#8
   @ ~/.julia/packages/PkgDeps/6nJkw/src/PkgDeps.jl:187 [inlined]
 [4] users(pkg_name::String)
   @ PkgDeps ~/.julia/packages/PkgDeps/6nJkw/src/PkgDeps.jl:187
 [5] top-level scope
   @ REPL[10]:1
```

This is both a bit more scary and a bit less helpful than it could be. Especially when it comes to a package name typo; the package is called `ParameterJuMP` not `ParameterJUMP` (also this is a real example i ran into when trying using this package in practice for the first time today).

I wonder if
- the message could be improved to
  - be clearer on what went wrong
  - suggest similarly named packages 
  - direct users to the `pkg_registry_name` keyword 
- the function shouldn't error, but should instead show a message (e.g. as an `@info` or `@warn`), then return `nothing`

Example: 
```julia
julia> users("ParameterJUMP")
PackageNotFoundError: No package with the name "ParameterJUMP" was found in the "General" registry.
Perhaps you meant: "ParameterJuMP"
Or you can search in another registry using `users("ParameterJUMP"; pkg_registry_name="OtherRegistry")`
```
or
```julia
julia> users("ParameterJUMP")
┌ Info: The package "ParameterJUMP" was not found in the "General" registry.
│ Perhaps you meant: "ParameterJuMP"
└ Or you can search in another registry using `users("ParameterJUMP"; pkg_registry_name="OtherRegistry")`
```

**Comment by mattBrzezinski** [comment]
I really like your second example, right now I'm just trying to flesh in the functionality in a more general way and then come back around to clean it up.

I'm not too sure how to implement the `perhaps you meant` part, but I think we could just take the algorithm the `Pkg.jl` uses to find similarly named packages when attempting to create a new package. I don't remember the name of it off-hand, where in the code it is, but it shouldn't be too hard to find.

As for the `search in another registry`, could be useful to have in here. I think that once documentation is created it will help clear things up.

**Comment by ericphanson** [comment]
DataFrames does something like that when you misspell a column by the way; the code it uses is here: https://github.com/JuliaData/DataFrames.jl/blob/596a7b11c8152ba4f3a75246d358ddb7901628d8/src/other/index.jl#L268-L295

**Comment by mattBrzezinski** [comment]
> DataFrames does something like that when you misspell a column by the way

Mint! Thank you, the source for these functions are actually in [base](https://github.com/JuliaLang/julia/blob/549380d02215522e1c288cd4754429aaef8c04e7/stdlib/REPL/src/docview.jl#L609-L652).
